### ISSUE TITLE
The webdriver for IE does not starting on version 1.5.0+

### ISSUE THREAD

**Issue by kolyas-github** [sbtqa/page-factory#107]
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
                at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
                at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
                at org.openqa.selenium.ie.InternetExplorerDriverService.access$000(InternetExplorerDriverService.java:32)
                at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:167)
                at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
                at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:251)
                at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
                at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
                at ru.sbtqa.tag.pagefactory.drivers.TagWebDriver.createDriver(TagWebDriver.java:143)
                at ru.sbtqa.tag.pagefactory.drivers.TagWebDriver.getDriver(TagWebDriver.java:106)
                at ru.sbtqa.tag.pagefactory.PageFactory.getDriver(PageFactory.java:49)
                at ru.sbtqa.tag.pagefactory.PageFactory.getWebDriver(PageFactory.java:39)
                at ru.sbt.qa.selenium.react.stepdefs.impl.CommonStepsImpl.<init>(CommonStepsImpl.java:24)
                at ru.sbt.qa.selenium.react.stepdefs.base.StepDefsBase.getCommonSteps(StepDefsBase.java:20)
                at ru.sbt.qa.sanctions.ui.stepdefs.AuthorizationStepDefs.authorizedInSystem(AuthorizationStepDefs.java:16)
                at ?.* пользователь авторизован в системе(1812.feature:5)

**Comment by clicman** [comment]
Provide your application.properties and page-factory version, please.

**Comment by kolyas-github** [comment]
page-factory version - 1.6.2

[application.zip](https://github.com/sbtqa/page-factory/files/1757431/application.zip)

**Comment by 0I0u3uk** [comment]
@kolyas-github now it work?

**Comment by kolyas-github** [comment]
@0I0u3uk yes. Now it is work!
