### ISSUE TITLE
Error in stepdef findElementInBlock(String block, String elementType, String elementTitle) (GenericStepDefs)

### ISSUE THREAD

**Issue by kolyas-github** [sbtqa/page-factory#131]
```
public class GenericStepDefs {
    ...
    ...
    public void findElementInBlock(String block, String elementType, String elementTitle) throws 
    PageException {
            String[] packages = this.getClass().getCanonicalName().split("\\."); 
            String currentLanguage = packages[packages.length - 2]; 
            I18N i18n = I18N.getI18n(this.getClass(), new Locale(currentLanguage));
            ... 
            ...
    }
    ...
    ...
}
```

this.getClass() **returned** "ru.sbtqa.tag.pagefactory.stepdefs.ru.Stepdefs".
**In method** I18N.getI18n() **we send** "ru.sbtqa.tag.pagefactory.stepdefs.ru.Stepdefs".

```
public static final I18N getI18n(Class callerClass, Locale locale, String bundlePath) {
        String className = callerClass.getSimpleName().toLowerCase();
        String resourceFile = bundlePath + DELIMITER + className + DELIMITER + locale.getLanguage() + ".properties";
        LOG.debug("Loading i18n bundle from {}", resourceFile);
        if (BUNDLE_STORAGE.get(resourceFile) == null) {
            I18N bundle = new I18N();
            bundle.bundleFile = resourceFile;
            try (InputStream streamFromResources = I18N.class.getClassLoader().getResourceAsStream(resourceFile)) {
                InputStreamReader isr = new InputStreamReader(streamFromResources, BUNDLE_ENCODING);
                bundle.properties.load(isr);
            } catch (IOException | NullPointerException e) {
                throw new I18NRuntimeException("Failed to access bundle properties file", e);
            }
            ...
       }
      ...
}
```

**The local variable** "className" = "Stepdefs".
**The local variable** "resourceFile" = "i18n/stepdefs/ru.properties" - **this path was not found in file system.**
**So we got** I18NRuntimeException("Failed to access bundle properties file", e)

**Full stacktrace:**

```
Failed to access bundle properties file
ru.sbtqa.tag.qautils.i18n.I18NRuntimeException: Failed to access bundle properties file
        at ru.sbtqa.tag.qautils.i18n.I18N.getI18n(I18N.java:94)
        at ru.sbtqa.tag.qautils.i18n.I18N.getI18n(I18N.java:49)
        at ru.sbtqa.tag.pagefactory.stepdefs.GenericStepDefs.findElementInBlock(GenericStepDefs.java:139)
        at ru.sbtqa.tag.pagefactory.stepdefs.ru.StepDefs.findElementInBlock(StepDefs.java:57)
        at ✽.пользователь в блоке "50: Плательщик" находит текстовое поле "Значение"(src/test/resources/features/374.feature:32)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at ru.sbtqa.tag.qautils.i18n.I18N.getI18n(I18N.java:91)
        at ru.sbtqa.tag.qautils.i18n.I18N.getI18n(I18N.java:49)
        at ru.sbtqa.tag.pagefactory.stepdefs.GenericStepDefs.findElementInBlock(GenericStepDefs.java:139)
        at ru.sbtqa.tag.pagefactory.stepdefs.ru.StepDefs.findElementInBlock(StepDefs.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:31)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:25)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
        at cucumber.api.TestStep.executeStep(TestStep.java:102)
        at cucumber.api.TestStep.run(TestStep.java:83)
        at cucumber.api.TestCase.run(TestCase.java:58)
        at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)

```

@kosteman help me, please.
Thanks!

**Comment by kosteman** [comment]
fixed in 1.9.3
