### ISSUE TITLE
Действие "нажимает кнопку" не находит

### ISSUE THREAD

**Issue by NasakB** [sbtqa/page-factory#160]
На находит CoreStepDefs.click

   <dependency>
      <groupId>ru.sbtqa.tag.pagefactory</groupId>
      <artifactId>html-plugin</artifactId>
      <version>11.1.1</version>
    </dependency>

лог:
    * пользователь (нажимает кнопку) "Esc"                                                                                         # CoreStepDefs.action(String,String)
      ru.sbtqa.tag.pagefactory.exceptions.NoSuchActionError: There is no 'нажимает кнопку' method on 'class ru.sbt.qa.vivat.pages.MainPage
                at ru.sbtqa.tag.pagefactory.reflection.DefaultReflection.executeMethodByTitle(DefaultReflection.java:67)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action_aroundBody4(CoreSteps.java:90)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps$AjcClosure5.run(CoreSteps.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                at ru.sbtqa.tag.pagefactory.allure.JunitReporter.handleStep(JunitReporter.java:25)
                at ru.sbtqa.tag.pagefactory.aspects.JUnitCoreStepAspect.handleStep(JUnitCoreStepAspect.java:13)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action(CoreSteps.java:89)
                at ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.action(CoreStepDefs.java:49)
                at ✽.пользователь (нажимает кнопку) "Esc"(src/test/resources/features/123.feature:9)

**Comment by clicman** [comment]
просьба ишью закрвит и завести в https://github.com/sbtqa/page-factory-2/issues

**Comment by NasakB** [comment]
На странице
https://github.com/sbtqa/page-factory-2
В разделе контакты ссылка новый запрос указывает на эту репозиторию 
<img width="1063" alt="Снимок экрана 2019-04-21 в 19 31 08" src="https://user-images.githubusercontent.com/6865670/56472818-1bf81700-646c-11e9-8bb0-c6bf98aa4623.png">
