### ISSUE TITLE
TagWebDriver.getDriver() fails without page.load.timeout property with bad error message.

### ISSUE THREAD

**Issue by PavelAlennikov** [sbtqa/page-factory#98]
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at ru.sbtqa.tag.pagefactory.PageFactory.getTimeOutInSeconds(PageFactory.java:121)
	at ru.sbtqa.tag.pagefactory.drivers.TagWebDriver.createDriver(TagWebDriver.java:181)
	at ru.sbtqa.tag.pagefactory.drivers.TagWebDriver.getDriver(TagWebDriver.java:77)
	at Main.main(Main.java:6)

**Comment by clicman** [comment]
We need to supply default 20 seconds value and throw warning about it like:
There’s is no bla-bla property in application.properties. Failing back to default one {value}
